In [1]:
import pandas as pd

In [2]:
data= r"C:\Users\Lenovo\Downloads\Employee Sample Data - A.xlsx"
df= pd.read_excel(data)

task 1

In [3]:
df.head()

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55.0,2016-04-08,141604.0,0.15,United States,Seattle,2021-10-16
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59.0,1997-11-29,99975.0,0.00,China,Chongqing,NaT
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50.0,2006-10-26,163099.0,0.20,United States,Chicago,NaT
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26.0,2019-09-27,84913.0,0.07,United States,Chicago,NaT
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55.0,1995-11-20,95409.0,0.00,United States,Phoenix,NaT

In [4]:
df

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55.0,2016-04-08,141604.0,0.15,United States,Seattle,2021-10-16
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59.0,1997-11-29,99975.0,0.00,China,Chongqing,NaT
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50.0,2006-10-26,163099.0,0.20,United States,Chicago,NaT
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26.0,2019-09-27,84913.0,0.07,United States,Chicago,NaT
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55.0,1995-11-20,95409.0,0.00,United States,Phoenix,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,E03094,Wesley Young,Sr. Analyst,Marketing,Speciality Products,Male,Caucasian,33.0,2016-09-18,98427.0,0.00,United States,Columbus,NaT
996,E01909,Lillian Khan,Analyst,Finance,Speciality Products,Female,Asian,44.0,2010-05-31,47387.0,0.00,China,Chengdu,2018-01-08
997,E04398,Oliver Yang,Director,Marketing,Speciality Products,Male,Asian,31.0,2019-06-10,176710.0,0.15,United States,Miami,NaT
998,E02521,Lily Nguyen,Sr. Analyst,Finance,Speciality Products,Female,Asian,33.0,2012-01-28,95960.0,0.00,China,Chengdu,NaT
999,E03545,Sofia Cheng,Vice President,Accounting,Corporate,Female,Asian,63.0,2020-07-26,216195.0,0.31,United States,Miami,NaT

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   EEID           1000 non-null   object
 1   Full Name      998 non-null    object
 2   Job Title      999 non-null    object
 3   Department     998 non-null    object
 4   Business Unit  1000 non-null   object
 5   Gender         999 non-null    object
 6   Ethnicity      993 non-null    object
 7   Age            994 non-null    float64
 8   Hire Date      993 non-null    datetime64[ns]
 9   Annual Salary  989 non-null    float64
 10  Bonus %        992 non-null    float64
 11  Country        998 non-null    object
 12  City           998 non-null    object
 13  Exit Date      85 non-null     datetime64[ns]
dtypes: datetime64[ns](2), float64(3), object(9)
memory usage: 109.5+ KB

In [6]:
df.isna().sum()

EEID               0
Full Name          2
Job Title          1
Department         2
Business Unit      0
Gender             1
Ethnicity          7
Age                6
Hire Date          7
Annual Salary     11
Bonus %            8
Country            2
City               2
Exit Date        915
dtype: int64

task 2

In [7]:
df.dropna(inplace= True)

In [8]:
df.isna().sum()

EEID             0
Full Name        0
Job Title        0
Department       0
Business Unit    0
Gender           0
Ethnicity        0
Age              0
Hire Date        0
Annual Salary    0
Bonus %          0
Country          0
City             0
Exit Date        0
dtype: int64

In [9]:
df.duplicated()

0      False
7      False
14     False
40     False
61     False
       ...
963    False
982    False
983    False
991    False
996    False
Length: 84, dtype: bool

In [10]:
df

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55.0,2016-04-08,141604.0,0.15,United States,Seattle,2021-10-16
7,E04332,Luke Martin,Analyst,Finance,Manufacturing,Male,Black,25.0,2020-05-16,41336.0,0.00,United States,Miami,2021-05-20
14,E03496,Robert Yang,Sr. Analyst,Accounting,Speciality Products,Male,Asian,31.0,2017-11-04,97078.0,0.00,United States,Austin,2020-03-09
40,E01754,Owen Lam,Sr. Business Partner,Human Resources,Speciality Products,Male,Asian,30.0,2017-05-29,86317.0,0.00,China,Chengdu,2017-07-16
61,E00502,Natalia Salazar,Sr. Analyst,Accounting,Manufacturing,Female,Latino,44.0,2019-01-02,74691.0,0.00,Brazil,Manaus,2020-07-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
963,E03305,Cooper Jiang,Analyst II,Accounting,Corporate,Male,Asian,49.0,2019-07-25,50883.0,0.00,China,Chongqing,2021-03-02
982,E03247,Aaliyah Mai,Vice President,IT,Speciality Products,Female,Asian,57.0,2016-11-11,246589.0,0.33,United States,Phoenix,2017-03-26
983,E02703,Austin Vang,Manager,Marketing,Speciality Products,Male,Asian,49.0,2018-05-20,119397.0,0.09,China,Beijing,2019-03-14
991,E03430,Leo Herrera,Sr. Business Partner,Human Resources,Research & Development,Male,Latino,48.0,1998-04-22,85369.0,0.00,Brazil,Manaus,2004-11-27
996,E01909,Lillian Khan,Analyst,Finance,Speciality Products,Female,Asian,44.0,2010-05-31,47387.0,0.00,China,Chengdu,2018-01-08

task 3

In [11]:
df.iloc[:5]

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55.0,2016-04-08,141604.0,0.15,United States,Seattle,2021-10-16
7,E04332,Luke Martin,Analyst,Finance,Manufacturing,Male,Black,25.0,2020-05-16,41336.0,0.00,United States,Miami,2021-05-20
14,E03496,Robert Yang,Sr. Analyst,Accounting,Speciality Products,Male,Asian,31.0,2017-11-04,97078.0,0.00,United States,Austin,2020-03-09
40,E01754,Owen Lam,Sr. Business Partner,Human Resources,Speciality Products,Male,Asian,30.0,2017-05-29,86317.0,0.00,China,Chengdu,2017-07-16
61,E00502,Natalia Salazar,Sr. Analyst,Accounting,Manufacturing,Female,Latino,44.0,2019-01-02,74691.0,0.00,Brazil,Manaus,2020-07-08

In [12]:
df.loc[df.index[:5], "Age"] += 1
df.loc[df.index[:5], "Annual Salary"] +=1000

task 4

In [19]:
max_row = df.loc[df["Annual Salary"].idxmax()]
print(max_row)

EEID                          E03247
Full Name                Aaliyah Mai
Job Title             Vice President
Department                        IT
Business Unit    Speciality Products
Gender                        Female
Ethnicity                      Asian
Age                             57.0
Hire Date        2016-11-11 00:00:00
Annual Salary               246589.0
Bonus %                         0.33
Country                United States
City                         Phoenix
Exit Date        2017-03-26 00:00:00
Name: 982, dtype: object

task 5

In [21]:
dept_summary = df.groupby("Department")[["Age","Annual Salary"]].mean()
dept_summary

                       Age  Annual Salary
Department
Accounting       43.000000  100259.428571
Engineering      45.529412  114851.176471
Finance          38.000000  114134.000000
Human Resources  45.545455   72502.909091
IT               44.866667   95484.533333
Marketing        39.866667  124392.533333
Sales            43.100000   97594.100000

task 6

In [22]:
dept_eth_summary = df.groupby(["Department","Ethnicity"]).agg({
    "Age": ["max","min"],
    "Annual Salary": "median"
})
dept_eth_summary

                            Age       Annual Salary
                            max   min        median
Department      Ethnicity
Accounting      Asian      49.0  32.0       74480.5
                Caucasian  55.0  29.0      144231.0
                Latino     58.0  45.0       87230.0
Engineering     Asian      60.0  30.0       91300.5
                Black      45.0  27.0      128657.5
                Caucasian  58.0  41.0       96059.5
                Latino     44.0  30.0      189290.0
Finance         Asian      44.0  27.0      131183.0
                Black      26.0  26.0       42336.0
                Caucasian  51.0  25.0      159386.0
                Latino     54.0  34.0      108268.0
Human Resources Asian      58.0  31.0       54051.0
                Black      41.0  41.0       49186.0
                Caucasian  54.0  38.0       69647.0
                Latino     48.0  45.0       68386.5
IT              Asian      57.0  45.0       82162.0
                Black      56.0  28.0       95899.0
                Caucasian  57.0  42.0       75354.0
                Latino     48.0  26.0       71727.0
Marketing       Asian      52.0  27.0      119397.0
                Black      65.0  30.0      138951.5
                Caucasian  34.0  34.0       83066.0
                Latino     29.0  29.0      129541.0
Sales           Asian      63.0  25.0       70041.5
                Black      40.0  40.0       62411.0
                Latino     53.0  39.0      147966.0

In [23]:
output_path = "Employee_Analysis_Output.xlsx"

with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
    df.to_excel(writer, sheet_name="Cleaned_Data", index=False)
    dept_summary.to_excel(writer, sheet_name="Dept_Averages")
    dept_eth_summary.to_excel(writer, sheet_name="Dept_Ethnicity_Stats")

print("Saved to:", output_path)

Saved to: Employee_Analysis_Output.xlsx

In [24]:
import os
print(os.getcwd())

C:\Users\Lenovo